#stages:
#  - test
#  - build
#  - deploy
#
#code_quality:
#  image: node:16.12.0
#  stage: test
#  before_script:
#    - npm ci
#  script:
#    - npm run eslint
#    - npm run stylelint
#    - npm run prettier-check
#  only:
#    - main
#
#build:
#  image: node:16.12.0
#  stage: build
#  before_script:
#    - npm ci
#  script:
#    - npm run build
#  artifacts:
#    paths:
#      - dist
#  only:
#    - main
#
#deploy:
#  image: alpine:latest
#  stage: deploy
#  before_script:
#    - apk update && apk add rsync openssh
#    - mkdir ~/.ssh
#    - chmod 600 ~/.ssh
#    - echo "$SSH_PRIVATE_KEY_GHU" >> ~/.ssh/id_rsa
#    - chmod 600 ~/.ssh/id_rsa
#    - echo "$SSH_KNOWN_HOSTS_GHU" >> ~/.ssh/known_hosts
#    - chmod 600 ~/.ssh/known_hosts
#  script:
#    - rsync -a --delete dist/ roman@194.87.111.12:/home/roman/gh-users/dist
#  only:
#    - main
